---

- name: creating tags
  hosts: all
  gather_facts: no
  become: true
  tasks:
    - name: user creation
      user:
        name: lunch
        password: chicken
        uid: 1150
        comment: "taste bad"
      tags: user_creation
    - name: create directory
      file:
        name: /home/ubuntu/tags
        state: directory
      tags: dir_creation
    - name: copy a file
      copy:
        src: /etc/passwd
        dest: /tmp/tag

